# Generated by Django 4.1.7 on 2023-03-06 13:27

import django.contrib.auth.password_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_messages_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=120, validators=[django.contrib.auth.password_validation.validate_password]),
        ),
    ]
